#!/bin/bash

r.l2r "$@"

# TEST: r0.1
# r0 daint '$SCRATCH/r0/t1'
# ssh daint ls -d '$SCRATCH/r0/t1'  > r0.out.txt
#

# TEST: r0.2
# r0 daint '$SCRATCH/r0/t1' - hostname   \
#   | awk '/^daint/{print "OK"}' > r0.out.txt
#
